[package]
name = "edifact-types"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_edifact = "0.1"
#serde_edifact = { path = "../serde_edifact", features = ["debug"] }

[features]
default = ["d00b"]
d00b = []