[package]
name = "edifact-types"
version = "0.3.0"
edition = "2021"
authors = ["Jens Walter <jens@apimeister.com>"]
license = "MIT OR Apache-2.0"
keywords = ["edi","edifact"]
repository = "https://github.com/apimeister/edifact-types/"
documentation = "https://docs.rs/edifact-types/"
description = "Bindings for the Edifact standard"

[dependencies]
serde = { version = "1", features = ["derive"] }
strum_macros = "0.24"
strum = "0.24"
proc-macro2 = "1"
quote = "1.0"
syn = { version = "1.0", features = ["parsing", "extra-traits"] }
macros = { path = "./macros", version = "0.1"}

[features]
default = ["d00b","d95b"]
d00b = []
d95b = []