[package]
name = "macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
name = "macros"

[dependencies]
heck = "0.4"
proc-macro2 = "1.0"
quote = "1.0"
rustversion = "1.0"
syn = { version = "1.0", features = ["parsing", "extra-traits"] }
